package linkserver

const (
	MSG_CLIENT_TO_PROXY = 1
	MSG_CLIENT_TO_HALL  = 2
	MSG_CLIENT_TO_GAME  = 3
	MSG_HALL_TO_PROXY   = 4
	MSG_GAME_TO_PROXY   = 5
	MSG_HALL_TO_MISC    = 6
	MSG_GAME_TO_MISC    = 7
)
